#!/usr/bin/env bash
# Displays Best School 10 times with a tweak

a=0

while [ $a -lt 10 ]
do
    if [ $a -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((a++))
done
